server:
  port: 8888
spring:
  application:
    name: config-server
#add the uri of the git repo that has the yml files
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Shristihub/intuitrepo.git

#access the yml file
#http://localhost:8888/product-info.yml