server:
  port: 8082

#import the config server to get the git uri
spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: product-catalog
eureka:
  client:
    service-url:
      default-zone: http://eureka-registry