server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intuitdb
    username: root
    password: root
  application:
    name: product-inventory

#jpa properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      default-zone: http://eureka-registry